# Generated by Django 3.1 on 2020-08-15 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'category',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('nutrition_grade', models.CharField(blank=True, max_length=1, null=True)),
                ('barcode', models.CharField(max_length=255)),
                ('url', models.CharField(blank=True, max_length=255, null=True)),
                ('url_pic', models.CharField(blank=True, max_length=255, null=True)),
                ('store', models.CharField(blank=True, max_length=255, null=True)),
                ('prd_cat', models.SmallIntegerField()),
                ('fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('saturated_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('sugar', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('salt', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            options={
                'db_table': 'product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='food.category')),
            ],
            options={
                'db_table': 'category_product',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_prd_barcode', models.CharField(max_length=255)),
                ('category_product_product_id', models.IntegerField()),
                ('category_product_category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='food.categoryproduct')),
            ],
            options={
                'db_table': 'favourite',
                'managed': True,
            },
        ),
    ]
